### ISSUE TITLE
warn Unable to resolve version 2.2.0 for ansi-styles

### ISSUE THREAD

**Issue by ryanmcdonough** [chalk/ansi-styles#19] opened 2016-04-01 08:55 UTC
I've looked at the issue that relates to 2.2.0 being unpublished, I've ran NPM shrinkwrap and change items to 2.2.1 - however I'm still getting:

warn Unable to resolve version 2.2.0 for ansi-styles

appearing multiple times during jspm install causing the entire thing to fail.

Am I missing something here?

[error.txt](https://github.com/chalk/ansi-styles/files/199269/error.txt)

[npm-shrinkwrap.txt](https://github.com/chalk/ansi-styles/files/199266/npm-shrinkwrap.txt)

**Comment by Qix-** [comment] 2016-04-01 09:17
Does [this help](https://github.com/chalk/ansi-styles/issues/15#issuecomment-202595595) at all?

**Comment by ryanmcdonough** [comment] 2016-04-01 11:00
@Qix- Sadly not, it's on a build server this is happening so the environment is trashed everytime so it's a fresh jspm each time.

**Comment by Qix-** [comment] 2016-04-01 22:08
Can you bump Chalk to version 1.1.3? This shouldn't be happening, your npm-shrinkwrap.txt looks fine.

It could be that the CI you're using is caching modules or something, or it's behind a private registry. Versions should be fixed now, so anything like this is generally a caching problem of some sort.

**Comment by patrickmichalina** [comment] 2016-04-04 04:35
What is going on with this? I am getting the same error.

**Comment by Qix-** [comment] 2016-04-04 04:37
@patrickmichalina Have you tried everything listed above? If so, I'm pretty sure it's a bug with jspm.

**Comment by patrickmichalina** [comment] 2016-04-04 05:00
@Qix- Yes, I have tried clearing both npm and jspm caches. Neither resolves the issue directly. With JSPM I think the real fix is to delete the entire "map" object in the config.js file (sometimes named jspm.config.js). After that do a jspm cache-clear and should fix it right up.

**Comment by Qix-** [comment] 2016-04-04 05:09
@patrickmichalina can you confirm that worked?

**Comment by patrickmichalina** [comment] 2016-04-04 05:10
Yes sorry. It worked. I used that method to fix my project.

**Comment by Qix-** [comment] 2016-04-04 05:22
@ryanmcdonough can you try @patrickmichalina's solution and see if it works for you? Not sure if this something that is done in the project itself or if the CI will need to be fixed.

**Comment by patrickmichalina** [comment] 2016-04-04 05:23
@ryanmcdonough @Qix- Since this file is stored in source control, this fix works in CI. I can confirm. Deployed with VSTS online using this fix.

**Comment by Qix-** [comment] 2016-04-04 05:24
Great! I'm going to go ahead and close this.

@ryanmcdonough if this *doesn't* end up working for you, let me know. :+1:

Thanks for the help @patrickmichalina!

**Closed by Qix-** 2016-04-04 05:24 UTC

**Comment by ryanmcdonough** [comment] 2016-04-04 13:01
@Qix- @patrickmichalina that worked perfectly. Well in my case I upaed the maps in the config to 1.1.3 rather than cleared them and it worked.

**Comment by Qix-** [comment] 2016-04-04 17:45
Glad to hear it! Thanks again for all the help!
